idf_component_register(
    SRCS
        "main.c"
        "wifi_connect.c"
        "take_picture.c"
        "web_capture.c"
        "web_stream.c"
        "driving.cpp"
        "driving_dots.c"
        "dots_algo.c"
        "dot_detection.c"
        "my_platform.c"
    INCLUDE_DIRS "."
    PRIV_REQUIRES
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        nvs_flash
        esp_timer
        esp_psram
        esp_jpeg
        esp_driver_gpio
        esp_driver_ledc
        lwip
        esp32-camera
        bluepad32
        btstack
)