idf_component_register(
    SRCS
        "main.c"
        "wifi/wifi_connect.c"
        "camera-logic/take_picture.c"
        "wifi/web_stream.c"
        "wifi/web_log.c"
        "driving-logic/driving.cpp"
        "object-detection/dot_detection.c"
        "driving-logic/my_platform.c"
        "comms/column_link.c"
    INCLUDE_DIRS "." "camera-logic" "comms" "driving-logic" "object-detection" "wifi"
    PRIV_REQUIRES
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        nvs_flash
        esp_timer
        esp_psram
        esp_jpeg
        esp_driver_gpio
        esp_driver_ledc
        lwip
        esp32-camera
        bluepad32
        btstack
)